{% set name = "libdrs" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v3.0.1.tar.gz
  sha256: df14b26ce57bb71722f48778882b3acf58dff435114fbbf61a3d2e2654c6d851

build:
  number: 2
  skip: True  # [win] 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - libnetcdf >=4.5
    - g2clib
  run:
    - libnetcdf >=4.5
    - g2clib

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a 

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  summary: 'Data Retrieval and Storage DRS software C library'
  description: |            
    libdrs is suitable for the data generated and used in climate model research. 
    It is oriented toward use with models generating very large datasets on 
    supercomputers, as well as with graphics workstations used for analysis and 
    display of smaller subsets of data. 
  dev_url: http://github.com/UV-CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
