{% set name = "libdrs" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CDAT/libdrs/archive/v{{ version }}.tar.gz
  sha256: bb36d6545fc330348f7b2f665b37da3a4b356f68adcdd1ae01a79c5c216a08f7

build:
  number: 1000
  skip: True  # [win] 

requirements:
  build:
    - {{ compiler('c') }}        # need gcc7 to link library
    - {{ compiler('fortran') }}   # (_gmalloc_fortran) issue without gfortran7
  host:
    - libnetcdf 
    - g2clib
  run:
    - libnetcdf 
    - g2clib

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a 

about:
  home:  http://cdat.llnl.gov
  summary: 'Data Retrieval and Storage DRS software Fortran library'
  license: BSD
  license_file: bsd-3-clause.txt
  description: |
    libdrs is suitable for the data generated and used in climate model research.
    It is oriented toward use with models generating very large datasets on
    supercomputers, as well as with graphics workstations used for analysis and
    display of smaller subsets of data.
  dev_url: http://github.com/UV-CDAT/libdrs



extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
