{% set name = "libdrs" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/libdrs/archive/v3.0.tar.gz
  sha256: b587c06b13844e7d21ab43017da06175b0d344763e40c44b4593ffb766104388

build:
  number: 0
  skip: True  # [win] 

requirements:
  build:
    - libnetcdf 4.4.*
    - g2clib
    - gcc
  run:
    - libnetcdf 4.4.*
    - g2clib
    - libgcc

test:
  commands:
    - test -f $PREFIX/lib/libdrs.a 

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  summary: 'Data Retrieval and Storage DRS software C library'
  description: |            
    libdrs is suitable for the data generated and used in climate model research. 
    It is oriented toward use with models generating very large datasets on 
    supercomputers, as well as with graphics workstations used for analysis and 
    display of smaller subsets of data. 
  dev_url: http://github.com/UV-CDAT/libdrs

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
