travis:
  secure:
    BINSTAR_TOKEN: eGfY02RfIxzeVtQbemf0GCm4L8iV0e8en4adfBjXBeghT6SDFLghHidN2eozCP8BffgwRPW2vNSYQi+UaCOJrAnjpF0WAPRqC4ycMhdg1nHcGqhLlS0nn5qdj9tByCArYLmw42v2kRbPfUM0b86wp+nLJJp3DJ3vYzhQQYesyFZVfD8qOykZNPVjQJaKynEo1OURWmu0E+mQA8IlM3WwlO/emPyS9b7pm8LAOOM5aNxiTznxrjDiRHzp8v/UIB65Ezdlur3lKkN1xevqZ5eBMEnZpdDeMbHTTzMeaOm8sR+T4XdwBW3mhy96VHyT5UjrLx6W6NSWczOf+r6xNVUnYIxRzmDbfjX2CJDO5Aju4BVaX7olD6gdxaE4duPh2ukFKAJdyiRG9RPHL07c2gQCq7QIjaPCrdN4gFeU0UProHdwQBVMytRoo7NAAwYeMgF0SVZXLDa2Y5uhRpCektXZGYp4jGXcxsNFHBe7feNYYvUn/7BETdvWRHWRyeMy30Ifl3e2XFVXiQFg7qH+p2oDVkrPFrkK8W/z2YZ3WaxDY1zSPZc1DtTTr/33ub+U7Gg/NC07VpsfoiZnPxCQwWunbkSXnoM/nhQaNkWhH4hGQkM2FpvmpUzlxvLwiyApxs7qhbD/68v4JNbqcSYlGPc5WkTg1M+sVQnx3qKbp9alBrg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
