appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZVX2QAz2f7qfB5oGAf5WNc/WJ8050Ni0xtF18kwLnlHCn8zZgYAc67upsYzLA6Lcagb6vZZiz6/80X5Td+g+gjKO6PR+rbojMiXac6RLXf8cYUwEoriTsrYhs8/wmqIZaKnzXPhkjtJgtwfLM7lQ9FiSFvO/o1qI/JFnNzzvYlZFpeZ0alTOdte80iPL6gLniZCDDf2aj0mswwFBR7yaOIded62o9/Il96w39j6I/eHu7WZdi57TAPKIaIc3uCjhh1wWoKmO0mfvWkZSyCXe3sCwu9VdUkMKD0Ghys1WGQJqmTi2FmECIgRhcUowM19zLWRwVWf3OOiu8sv84RiPd5UQgP/CYhUl7FpQ74I+uiny4HavtBbajPo1rOWz7iIZvYlrRJlI3bMKnoqmVuQlx9ulaCbQ5RhOtSw1rHWOZ5WW62BwOMoVOuqo77UdnAOWRbAa1UfmiJimxMCta/GziXPrkxlMF77qyPsoaV+APd9jn3zuLfUTu1kLv52tIim0nO60vcuolZ4rnw1B8+pgwLiBslwTKSMpcj2DHRRIXit/c+Ki2NO+SlFrGQPUlLwfCwReHh7fvqOziHkR2M/LjmfhiisJwYho7qpOMKPOlfwgWepZ69qrnbg8VCdAZ553UELK6Rb+P0lxg/uRdPOK4bhu0l7j4LkrWmi980MG+hA=}
