travis:
  secure:
    BINSTAR_TOKEN: LzLtmrrNbRfFME2RQo4e7MbRwAWWvzbssHw1Gg3baI58NF5232mIrc4v1sKWhv/NdA5k2N3GGTE8ZMQeAvnsX8uVNzQWTQxXC6KCXD5n+3Q+sj/dl8KT2X5ranwDNPiPWyEJUytGxDnmK0Tjib6CI2U2lT5WYR0h4zzJyrToVEstTMMcEjTXsJHAs+imkHTIsi032nyW6gyz8jve7Ws5rXAeQN44dySHMMpSrDw5yTTgRkk03PSYiWnnzWiHgj8EEm40cDBQGyx0MuJPwOunKbVkUNHbi2DAb5+u0Fi5peW7HYgfFJju/iUm2Fy4zjFnoHXoAJoRw01OTZwD4AadaIDmt3rBT29OQMCIBO4fTKlr/8DXpX+rjSV2M25vym4fAXOK+B/CHcrVonT0j0GQnZjNJhS7cdWci0oekLeEVn4lvo6KbCUcL3vTeT9xjHzSPvR/vPowv3mjTG86p/S+8D8eleuFnS3qb8KxiCoHhHvWEpjD0nwWGb6cOUPleHZ5q0pA2aP5ywYczDAWPswxiL0kW+cf2ihFj0jZWrRQg9APtpyxqeNwiYVSyrzA2WpTDJbW2MnhuXPp1gDSTdRH2yum3h915xZ8uOEw4k424/YL2L/gBIR0ReRnMYHE0XaVNJXAqZnLBfLjPk2/RXVBqSF4EQ+l5/tbz8h02ZHlGOg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
